### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-world#55]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

- [x] Explain how to make a contribution (Contributing MD)
- [x] Include the Standard Code of Conduct
- [x] Either add LICENSE top-level referencing other license files or remove CC license
- [x] Identify the Core Maintainers

**Comment by disassembler** [comment]
@ThatGuyLLC a number of the things you're requesting are already done (and have been for almost a year). Did you look at the repository before posting this?

**Comment by ThatGuyLLC** [comment]
HI @disassembler, I went through using Github inisghts community tool and it has everything minus the Readme counted as missing. Is there a reason for that?

**Comment by disassembler** [comment]
@manveru is there a reason we need two licenses (apache and CC)? It might simplify things to just drop it to Apache only.
